### ISSUE TITLE
GH Action to close stale issues/PRs

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#119]
https://github.com/marketplace/actions/close-stale-issues

**Comment by NissesSenap** [comment]
A example implementation of stale: https://github.com/grafana-operator/grafana-operator/pull/544

**Comment by bittrance** [comment]
There was some discussion live on this topic. It seems that we have a majority for viewing this project's issues as a road map/bug tracker (i.e. where most issues represent a long-lived ambition) rather than a work queue (where the tail can safely be assumed to be stale). Hence, this issue can be closed wont-fix. Ok @simongottschlag ?

**Comment by simongottschlag** [comment]
@bittrance ok! 👍
