### ISSUE TITLE
Add module for Popeye

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#366]
https://github.com/derailed/popeye

**Comment by bittrance** [comment]
Some questions:
- can it support custom resources somehow? (I'll borrow the baton from _phillebaba and whisper *Rego support*)
- this mixes infrastructure and app level checks; do you see that it should be included for one of those or potentially twice with different configs?
- some parts of this linting looks like monitoring? Is that good or bad? (If there is an "app level" report, it may be useful because that may reach developers which do not normally consume monitoring info.)
- do you see it running as a periodic job? If so, how will the report be made available?

**Comment by simongottschlag** [comment]
@bittrance I haven't gone through it fully yet, but my thought was that it should be running in the clusters and expose Prometheus metrics that can be included in reports to the tenants, to help them with their continuous improvement.

**Comment by landerss1** [comment]
Implemented in #1239 .

Popeye does not support CRDs. We will use it to lint our tenants. Reports will be saved to a storage account file share.
