### ISSUE TITLE
kubernetes: tenant namespaces should never be deleted

### ISSUE THREAD

**Issue by simongottschlag** [XenitAB/terraform-modules#511]
A tenant namespace should never be deleted using terraform, it can cause issues for Flux and needs to be handled manually. This can be handled through the [lifecycle meta-argument](https://www.terraform.io/language/meta-arguments/lifecycle) `prevent_destroy = true` for the namespaces: 

To keep track of tenants that has been removed but still have namespaces in clusters, a new feature can be introduced where we add a label to the namespaces after they are created (`managed: true` or something like that) and allow this label to be removed while keeping the actual namespace. This should potentially make it possible to identify the "stale" namespaces by finding all tenant namespaces without the tag.

As of now, it's not possible to add labels through the kubernetes provider. The following PR tries to introduce the concept `kubernetes_label` to enable this: [kubernetes_label: Make it possible to add labels to resources #1562](https://github.com/hashicorp/terraform-provider-kubernetes/pull/1562)

Tasks needed to complete this issue:

- [ ] Add `prevent_destroy` to tenant namespaces
- [x] Merge & release `kubernetes_label` in the terraform provider
- [ ] Add `kubernetes_label` to tenant namespaces

**Comment by simongottschlag** [comment]
Now (or as soon as it's released) labels can be set: https://github.com/hashicorp/terraform-provider-kubernetes/pull/1616

**Comment by landerss1** [comment]
We can certainly add a lifecycle meta-argument to prevent tenant namespaces from being destroyed (https://github.com/XenitAB/terraform-modules/blob/main/modules/kubernetes/aks-core/namespace.tf#L1). Since all tenant namespaces are created from the same resource, this means that once a tenant namespace has been created, the namespace can never be removed from the input variable unless we intend to delete the namespace. 

The second part of this issue is about keeping track of namespaces that have been deleted outside of Terraform. The question is why we should bother about this? The only drawback I can see is that there will be a "dead" resource in the Terraform state, but is that really an issue? And, how would labeling namespaces really solve anything, wouldn't it just create another task of having to track labels instead? As an alternative, we could easily create a script that pulls all namespaces from the state and compares with namespaces in k8s.

**Comment by landerss1** [comment]
Fixed by [1158](https://github.com/XenitAB/terraform-modules/pull/1158).
