### ISSUE TITLE
Error accessing Key Vault when deploying locally

### ISSUE THREAD

**Issue by Bakernator** [XenitAB/terraform-modules#969]
When deploying the governance module locally with a user account the deployment fails with the error message below. To solve this the user account must be manually added to the Key Vault access list after the initial deploy and on the second deploy the error is gone. The issue here is that the governance module requires manual intervention and at least two deploys to complete...

`module.governance-regional.azurerm_key_vault_secret.delegate_kv_aad["core"]: Creating...
╷
│ Error: checking for presence of existing Secret "x" (Key Vault "https://x/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=00000000-0000-0000-0000-000000000000;oid=00000000-0000-0000-0000-000000000000;numgroups=12;iss=https://sts.windows.net/00000000-0000-0000-0000-000000000000/' does not have secrets get permission on key vault 'x;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
│
│   with module.governance-regional.azurerm_key_vault_secret.delegate_kv_aad["core"],
│   on .terraform/modules/governance-regional/modules/azure/governance-regional/delegate-kv-sp.tf line 19, in resource "azurerm_key_vault_secret" "delegate_kv_aad":
│   19: resource "azurerm_key_vault_secret" "delegate_kv_aad" {
│
╵
╷
│ Error: checking for presence of existing Secret "x" (Key Vault "https://x/"): keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="The user, group or application 'appid=00000000-0000-0000-0000-000000000000;oid=00000000-0000-0000-0000-000000000000;numgroups=12;iss=https://sts.windows.net/00000000-0000-0000-0000-000000000000/' does not have secrets get permission on key vault 'x;location=westeurope'. For help resolving this issue, please see https://go.microsoft.com/fwlink/?linkid=2125287" InnerError={"code":"AccessDenied"}
│
│   with module.governance-regional.azurerm_key_vault_secret.sub_reader_sp,
│   on .terraform/modules/governance-regional/modules/azure/governance-regional/sp-sub-reader.tf line 13, in resource "azurerm_key_vault_secret" "sub_reader_sp":
│   13: resource "azurerm_key_vault_secret" "sub_reader_sp" {
│
╵
make: *** [Makefile:85: apply] Error 1`

**Comment by simongottschlag** [comment]
Hi @Bakernator!

This is by design when you configure the variable `delegate_sub_groups` to `false` in `governance-global`. If you create the "global" groups first and add the admins to them, then set it to `true` - it will work.

See here: https://github.com/XenitAB/terraform-modules/blob/cf312268e13a1d0f94747c1a2b149be3497cc4a5/modules/azure/governance-global/variables.tf#L46-L50

If you don't want to use the "global" groups as documented [here](https://github.com/XenitAB/terraform-modules/tree/main/modules/azure#azure-service-principal-owner) then the only options are to either run once, add yourselves to the groups and then run again or let the pipelines handle it.
